// This file is @generated by prost-build.
/// Configuration file for ProcMon detector
#[derive(serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct ProcMonConfig {
    /// setuid hook config.
    #[prost(message, optional, tag = "1")]
    pub setuid: ::core::option::Option<HookConfig>,
    /// capset hook config.
    #[prost(message, optional, tag = "2")]
    pub capset: ::core::option::Option<HookConfig>,
    /// prctl hook config.
    #[prost(message, optional, tag = "3")]
    pub prctl: ::core::option::Option<HookConfig>,
    /// create_user_ns hook config.
    #[prost(message, optional, tag = "4")]
    pub create_user_ns: ::core::option::Option<HookConfig>,
    /// ptrace_attach hook config.
    #[prost(message, optional, tag = "5")]
    pub ptrace_access_check: ::core::option::Option<HookConfig>,
    /// setgid hook config.
    #[prost(message, optional, tag = "6")]
    pub setgid: ::core::option::Option<HookConfig>,
    /// Collect IMA hashes for executed binaries.
    #[prost(bool, optional, tag = "8")]
    pub ima_hash: ::core::option::Option<bool>,
    /// GC period for PROCMON_PROC_MAP default 30 sec.
    #[prost(uint64, optional, tag = "9")]
    pub gc_period: ::core::option::Option<u64>,
}
/// Configuration file for FileMon detector.
#[derive(serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct FileMonConfig {
    /// security_file_open config.
    #[prost(message, optional, tag = "1")]
    pub file_open: ::core::option::Option<HookConfig>,
    /// security_path_truncate config.
    #[prost(message, optional, tag = "2")]
    pub path_truncate: ::core::option::Option<HookConfig>,
    /// security_path_unlink config.
    #[prost(message, optional, tag = "3")]
    pub path_unlink: ::core::option::Option<HookConfig>,
    /// security_path_symlink config.
    #[prost(message, optional, tag = "4")]
    pub path_symlink: ::core::option::Option<HookConfig>,
    /// security_path_chmod config.
    #[prost(message, optional, tag = "5")]
    pub path_chmod: ::core::option::Option<HookConfig>,
    /// security_path_chown config.
    #[prost(message, optional, tag = "6")]
    pub path_chown: ::core::option::Option<HookConfig>,
    /// security_sb_mount config.
    #[prost(message, optional, tag = "7")]
    pub sb_mount: ::core::option::Option<HookConfig>,
    /// security_mmap_file config.
    #[prost(message, optional, tag = "8")]
    pub mmap_file: ::core::option::Option<HookConfig>,
    /// security_file_ioctl config.
    #[prost(message, optional, tag = "9")]
    pub file_ioctl: ::core::option::Option<HookConfig>,
}
/// Configuration file for NetMon detector.
#[derive(serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct NetMonConfig {
    /// Ingress traffic connections
    #[prost(message, optional, tag = "1")]
    pub ingress: ::core::option::Option<HookConfig>,
    /// Egress traffic connections
    #[prost(message, optional, tag = "2")]
    pub egress: ::core::option::Option<HookConfig>,
}
/// Configuration file for GTFOBinsDetector.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GtfoBinsConfig {
    /// Block execution of GTFOBins binaries.
    #[prost(bool, tag = "1")]
    pub enforce: bool,
    /// GTFOBins executables names.
    #[prost(string, repeated, tag = "2")]
    pub gtfobins: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Rule definition. Scope and event predicates are used as logical conjunction.
#[derive(serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Rule {
    /// Name of the rule.
    #[prost(string, tag = "1")]
    #[serde(rename = "rule")]
    pub name: ::prost::alloc::string::String,
    /// Logical predicate describes scope this rule will be applied, e.g. process, container.
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub scope: ::prost::alloc::string::String,
    /// Logical predicate for describes event rule will be applied
    #[prost(string, tag = "3")]
    #[serde(default)]
    pub event: ::prost::alloc::string::String,
}
/// Hook or group of hooks configuration
#[derive(serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct HookConfig {
    /// Load eBPF programs
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// Filtering rules
    #[prost(message, repeated, tag = "2")]
    #[serde(default)]
    pub rules: ::prost::alloc::vec::Vec<Rule>,
}
